### ISSUE TITLE
Errors feeding MLAT back when using an external flightfeeder

### ISSUE THREAD

**Issue by mikeage** [ADSBexchange/wiki#1]
Hi, I followed the instructions at https://github.com/adsbxchange/wiki/wiki/Feed-using-data-from-FA-blue to point my local copy of adsbexchange-feed and adsbexchange-mlat to my flightfeeder, and I see my data appearing at adsbexchange. By default, this still tries to feed back to localhost:30104, which isn't listening:
```
Oct 11 10:31:52 raspberrypi adsbexchange-mlat[10765]: Beast-format results connection with 127.0.0.1:30104: [Errno 111] Connection refused
Oct 11 10:32:22 raspberrypi adsbexchange-mlat[10765]: Beast-format results connection with ::1:30104: [Errno 111] Connection refused
```

Changing it to point to 30104 on the flightfeeder also fails, since it appears like it doesn't listen for external connections:
```
Oct 11 10:36:54 raspberrypi adsbexchange-mlat[7403]: Beast-format results connection with 192.168.1.201:30104: [Errno 111] Connection refused
```

```
$ nmap 192.168.1.201 -p 30000-30007,30100-30110 -P0 | grep open
30002/tcp open     pago-services2
30003/tcp open     amicon-fpsu-ra
30005/tcp open     unknown
30105/tcp open     unknown
30106/tcp open     unknown
```

**Comment by wiedehopf** [comment]
Doesn't really matter apart from the log messages?

You can just remove the offending RESULTS line or make it `RESULTS=""`

You can install tar1090 locally and get a local map (it uses the jsons produced by adsbexchange-feed):
 https://github.com/wiedehopf/tar1090#tar1090

**Comment by mikeage** [comment]
It doesn't matter one bit -- it was more of a question as to whether the documentation should be updated or not. I wasn't clear on whether flightfeeders should accept MLAT from external sources.

**Comment by wiedehopf** [comment]
I didn't even know that myself.

Most people don't check the logs but i'll add a note about the mlat backfeed not being useful.
I suppose it might be worth mentioning you can add a local display to the machine you feed the data from.
